CREATE MESSAGE TYPE [//HWTRepository/LabVIEW/SQLMessage]
    AUTHORIZATION [dbo]
    VALIDATION = NONE;
	GO

	CREATE MESSAGE TYPE [//HWTRepository/LabVIEW/SQLMessageResponse]
    AUTHORIZATION [dbo]
    VALIDATION = NONE;

